-- =========================
-- DROP TABLES (order matters for FK constraints)
-- =========================
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS forms CASCADE;
DROP TABLE IF EXISTS form_templates CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS institutions CASCADE;

DROP TRIGGER IF EXISTS trg_audit_member_added ON users;
DROP FUNCTION IF EXISTS fn_audit_member_added();

-- =========================
-- INSTITUTIONS
-- =========================
CREATE TABLE institutions (
    institution_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    domain          VARCHAR(100),               -- e.g. manipal.edu (optional, for display)
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- DEPARTMENTS
-- =========================
CREATE TABLE departments (
    dept_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id  INTEGER NOT NULL,
    name            VARCHAR(100) NOT NULL,
    CONSTRAINT fk_dept_institution
        FOREIGN KEY (institution_id)
        REFERENCES institutions(institution_id)
        ON DELETE CASCADE
);

-- =========================
-- USERS
-- =========================
-- role:   admin | hod | faculty | student
-- status: pending (added by admin, not signed up yet)
--         active  (signed up and ready)
CREATE TABLE users (
    user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id  INTEGER,                    -- NULL only for platform-level if needed
    dept_id         INTEGER,                    -- NULL for admin role
    name            VARCHAR(100),               -- filled on signup
    email           VARCHAR(200) UNIQUE NOT NULL,
    password        VARCHAR(255),               -- filled on signup (NULL = pending)
    role            VARCHAR(20) NOT NULL
        CHECK (role IN ('admin', 'hod', 'faculty', 'student')),
    batch           INTEGER,                    -- year of joining, for students
    status          VARCHAR(20) DEFAULT 'pending' NOT NULL
        CHECK (status IN ('pending', 'active')),
    joined_at       TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_user_institution
        FOREIGN KEY (institution_id)
        REFERENCES institutions(institution_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_dept
        FOREIGN KEY (dept_id)
        REFERENCES departments(dept_id)
        ON DELETE SET NULL
);

-- =========================
-- FORMS
-- =========================
-- access_type values:
--   public      → everyone in institution
--   dept        → specific department
--   batch       → specific batch/year
--   role        → specific role (e.g. faculty only)
--   dept_batch  → e.g. CSE 2023 batch
--   dept_role   → e.g. CSE faculty only
CREATE TABLE forms (
    form_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id  INTEGER NOT NULL,
    title           VARCHAR(150) NOT NULL,
    description     TEXT,
    creator_id      INTEGER NOT NULL,
    access_type     VARCHAR(20) NOT NULL
        CHECK (access_type IN ('public', 'dept', 'batch', 'role', 'dept_batch', 'dept_role')),
    target_dept_id  INTEGER,                    -- FK to departments
    target_role     VARCHAR(20)
        CHECK (target_role IN ('admin', 'hod', 'faculty', 'student') OR target_role IS NULL),
    target_batch    INTEGER,                    -- specific batch year
    deadline        TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) DEFAULT 'open' NOT NULL
        CHECK (status IN ('open', 'closed')),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    form_code       VARCHAR(20) NOT NULL UNIQUE,
    report_released VARCHAR(5) DEFAULT 'no'
        CHECK (report_released IN ('yes', 'no')),
    theme_color     VARCHAR(20) DEFAULT 'emerald',
    allow_multiple  VARCHAR(5) DEFAULT 'no'
        CHECK (allow_multiple IN ('yes', 'no')),
    CONSTRAINT fk_forms_creator
        FOREIGN KEY (creator_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forms_institution
        FOREIGN KEY (institution_id)
        REFERENCES institutions(institution_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forms_dept
        FOREIGN KEY (target_dept_id)
        REFERENCES departments(dept_id)
        ON DELETE SET NULL
);

-- =========================
-- AUDIT LOGS
-- =========================
CREATE TABLE audit_logs (
    log_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id  INTEGER,
    action_type     VARCHAR(100) NOT NULL,
    user_id         INTEGER,
    form_id         INTEGER,
    metadata        TEXT,                       -- optional extra info (e.g. "imported 45 members")
    log_time        TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_audit_institution
        FOREIGN KEY (institution_id)
        REFERENCES institutions(institution_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_audit_form
        FOREIGN KEY (form_id)
        REFERENCES forms(form_id)
        ON DELETE SET NULL
);

-- =========================
-- QUESTIONS
-- =========================
CREATE TABLE questions (
    question_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         INTEGER NOT NULL,
    question_text   TEXT NOT NULL,
    question_type   VARCHAR(20) NOT NULL
        CHECK (question_type IN ('text', 'textarea', 'number', 'email', 'date', 'mcq')),
    is_required     SMALLINT NOT NULL CHECK (is_required IN (0, 1)),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_questions_form
        FOREIGN KEY (form_id)
        REFERENCES forms(form_id)
        ON DELETE CASCADE
);

-- =========================
-- OPTIONS
-- =========================
CREATE TABLE options (
    option_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id     INTEGER NOT NULL,
    option_text     TEXT NOT NULL,
    CONSTRAINT fk_options_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id)
        ON DELETE CASCADE
);

-- =========================
-- RESPONSES
-- =========================
CREATE TABLE responses (
    response_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    submitted_at    TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT fk_responses_form
        FOREIGN KEY (form_id)
        REFERENCES forms(form_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_responses_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================
-- ANSWERS
-- =========================
CREATE TABLE answers (
    answer_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id         INTEGER NOT NULL,
    question_id         INTEGER NOT NULL,
    answer_text         TEXT,
    answer_number       NUMERIC(10, 4),
    selected_option_id  INTEGER,
    CONSTRAINT fk_answers_response
        FOREIGN KEY (response_id)
        REFERENCES responses(response_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_answers_option
        FOREIGN KEY (selected_option_id)
        REFERENCES options(option_id),
    CONSTRAINT chk_one_answer_only CHECK (
        (answer_text IS NOT NULL AND answer_number IS NULL AND selected_option_id IS NULL)
        OR
        (answer_text IS NULL AND answer_number IS NOT NULL AND selected_option_id IS NULL)
        OR
        (answer_text IS NULL AND answer_number IS NULL AND selected_option_id IS NOT NULL)
    )
);

-- =========================
-- FORM TEMPLATES
-- =========================
CREATE TABLE form_templates (
    template_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    structure       TEXT NOT NULL
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Event Registration',
    'A standard form for collecting event attendee details.',
    '[{"text":"Full Name","type":"text","required":true},{"text":"Email Address","type":"text","required":true},{"text":"T-Shirt Size","type":"mcq","required":true,"options":["Small","Medium","Large","XL"]},{"text":"Dietary Restrictions","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Course Evaluation',
    'End of semester feedback collection.',
    '[{"text":"Rate the course difficulty (1-5)","type":"number","required":true},{"text":"Rate the instructor (1-5)","type":"number","required":true},{"text":"What did you like most about this course?","type":"text","required":false},{"text":"Would you recommend this course?","type":"mcq","required":true,"options":["Yes","No"]}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Faculty Feedback Form',
    'Detailed anonymous feedback for teaching faculty.',
    '[{"text":"Faculty Name","type":"text","required":true},{"text":"Subject","type":"text","required":true},{"text":"Teaching Quality (1-5)","type":"number","required":true},{"text":"Clarity of Explanation (1-5)","type":"number","required":true},{"text":"Interaction Level (1-5)","type":"number","required":true},{"text":"Additional Comments","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Quiz / Internal Test',
    'A standard multiple-choice quiz format.',
    '[{"text":"Student Name / Roll No","type":"text","required":true},{"text":"What does DBMS stand for?","type":"mcq","required":true,"options":["Database Management System","Data Base Multi System","Data Backup Management Structure","None of the above"]},{"text":"Which of the following is a DDL command?","type":"mcq","required":true,"options":["INSERT","UPDATE","CREATE","SELECT"]},{"text":"Explain the difference between Primary Key and Unique Key briefly (Optional)","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Leave Application (Student)',
    'Official leave request for students.',
    '[{"text":"Name / Roll No","type":"text","required":true},{"text":"From Date (DD/MM/YYYY)","type":"text","required":true},{"text":"To Date (DD/MM/YYYY)","type":"text","required":true},{"text":"Type of Leave","type":"mcq","required":true,"options":["Medical","Personal","Other"]},{"text":"Detailed Reason","type":"text","required":true}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Lab Feedback Form',
    'Feedback collection for laboratory sessions.',
    '[{"text":"Lab Name / Course Code","type":"text","required":true},{"text":"Equipment Quality (1-5)","type":"number","required":true},{"text":"Lab Instructor Helpfulness (1-5)","type":"number","required":true},{"text":"Overall Difficulty Level","type":"mcq","required":true,"options":["Easy","Medium","Hard"]},{"text":"Any specific suggestions?","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Doubt/Query Submission',
    'Direct question submission to faculty.',
    '[{"text":"Full Name","type":"text","required":true},{"text":"Subject / Topic","type":"text","required":true},{"text":"What is your question?","type":"text","required":true},{"text":"Priority Level","type":"mcq","required":false,"options":["High","Medium","Low"]}]'
);

-- =========================
-- TRIGGER FUNCTIONS & TRIGGERS
-- =========================

-- 1. Prevent forms from being created with a past deadline
CREATE OR REPLACE FUNCTION fn_form_deadline_check()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') OR (TG_OP = 'UPDATE' AND NEW.deadline IS DISTINCT FROM OLD.deadline) THEN
        IF NEW.deadline <= NOW() THEN
            RAISE EXCEPTION 'Form deadline cannot be in the past.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_form_deadline_check
BEFORE INSERT OR UPDATE ON forms
FOR EACH ROW
EXECUTE FUNCTION fn_form_deadline_check();

-- 2. Prevent responses on closed or expired forms
CREATE OR REPLACE FUNCTION fn_prevent_invalid_response()
RETURNS TRIGGER AS $$
DECLARE
    v_status   VARCHAR(20);
    v_deadline TIMESTAMPTZ;
BEGIN
    SELECT status, deadline INTO v_status, v_deadline
    FROM forms
    WHERE form_id = NEW.form_id;

    IF v_status = 'closed' OR v_deadline < NOW() THEN
        RAISE EXCEPTION 'Cannot submit response: Form is closed or expired.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_prevent_invalid_response
BEFORE INSERT ON responses
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_invalid_response();

-- 3. Audit form creation
CREATE OR REPLACE FUNCTION fn_audit_form_creation()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_logs (institution_id, action_type, user_id, form_id)
    SELECT u.institution_id, 'CREATED NEW FORM', NEW.creator_id, NEW.form_id
    FROM users u WHERE u.user_id = NEW.creator_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_audit_form_creation
AFTER INSERT ON forms
FOR EACH ROW
EXECUTE FUNCTION fn_audit_form_creation();

-- 4. Audit response submission
CREATE OR REPLACE FUNCTION fn_audit_response()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_logs (institution_id, action_type, user_id, form_id)
    SELECT u.institution_id, 'SUBMITTED RESPONSE', NEW.user_id, NEW.form_id
    FROM users u WHERE u.user_id = NEW.user_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_audit_response
AFTER INSERT ON responses
FOR EACH ROW
EXECUTE FUNCTION fn_audit_response();

-- 5. Audit member added by admin
CREATE OR REPLACE FUNCTION fn_audit_member_added()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.institution_id IS NOT NULL THEN
        INSERT INTO audit_logs (institution_id, action_type, metadata)
        VALUES (NEW.institution_id, 'MEMBER ADDED', NEW.email);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_audit_member_added
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION fn_audit_member_added();

-- =========================
-- FUNCTIONS
-- =========================

-- Get total number of responses for a form
CREATE OR REPLACE FUNCTION fn_get_response_count(p_form_id INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM responses
    WHERE form_id = p_form_id;
    RETURN v_count;
END;
$$ LANGUAGE plpgsql;

-- Check if a user can see a form based on access rules
-- Returns TRUE if the user's role/dept/batch matches the form's targeting
CREATE OR REPLACE FUNCTION fn_user_can_see_form(
    p_user_id   INTEGER,
    p_form_id   INTEGER
) RETURNS BOOLEAN AS $$
DECLARE
    v_user      RECORD;
    v_form      RECORD;
BEGIN
    SELECT role, dept_id, batch, institution_id
    INTO v_user FROM users WHERE user_id = p_user_id;

    SELECT access_type, target_dept_id, target_role, target_batch,
           institution_id, creator_id
    INTO v_form FROM forms WHERE form_id = p_form_id;

    -- Must be same institution
    IF v_user.institution_id != v_form.institution_id THEN
        RETURN FALSE;
    END IF;

    -- Admin and creator always see it
    IF v_user.role = 'admin' OR v_form.creator_id = p_user_id THEN
        RETURN TRUE;
    END IF;

    -- Check access type
    IF v_form.access_type = 'public' THEN
        RETURN TRUE;
    ELSIF v_form.access_type = 'dept' THEN
        RETURN v_user.dept_id = v_form.target_dept_id;
    ELSIF v_form.access_type = 'batch' THEN
        RETURN v_user.role = 'student'
           AND v_user.batch = v_form.target_batch;
    ELSIF v_form.access_type = 'role' THEN
        RETURN v_user.role = v_form.target_role;
    ELSIF v_form.access_type = 'dept_batch' THEN
        RETURN v_user.role = 'student'
           AND v_user.dept_id = v_form.target_dept_id
           AND v_user.batch = v_form.target_batch;
    ELSIF v_form.access_type = 'dept_role' THEN
        RETURN v_user.dept_id = v_form.target_dept_id
           AND v_user.role = v_form.target_role;
    END IF;

    RETURN FALSE;
END;
$$ LANGUAGE plpgsql;